spring.application.name=openaipdfreader
spring.datasource.url=jdbc:sqlserver://192.168.1.5:1434;databaseName=velotech_v3;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Velotech*1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#JPA properties
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
# Forces Hibernate to use the exact names defined in your @Column and @Table annotations
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl


############################################
# Multipart File Upload
############################################
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


############################################
# OpenAI Configuration
############################################
# ? Replace with your real API key OR use environment variable
openai.api.key=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
openai.timeout=60


############################################
# OCR - Tesseract (WINDOWS)
############################################
# Make sure this path exists on your machine
tesseract.datapath=C:/Program Files/Tesseract-OCR/tessdata
tesseract.language=eng


############################################
# Logging
############################################
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.learn.jwt_demo=DEBUG



############################################
# Error Handling
############################################
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
